### ISSUE TITLE
Enabling KAMP Purging

### ISSUE THREAD

**Issue by rednet1** [qidi-community/Plus4-Wiki#17]
I am using the new bleed line described, now I have a problem in a project I put as brim width 30 mm, the brim has passed above the bleed line

**Comment by stew675** [comment]
Unfortunately the KAMP purging is performed by a Macro script on the printer itself, and is independent of the Gcode that your slicer emits.  There is no way to resolve this in the code.

One thing you can do is to watch the start of the print and flick the purge line out of the way immediately after it is laid down.
